[project]
name = "geotoolbox"
version = "0.1.0"
description = "A collection of tools for geospatial, geotechnical, and statistical data processing and modelling"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Exneyder A. Montoya-Araque", email = "eamontoyaa@eafit.edu.co" },
  { name = "Daniel F. Ruiz", email = "dfruizr@eafit.edu.co" },
  { name = "Universidad EAFIT"},
]
requires-python = ">=3.12"
dependencies = [
  "numpy",
  "pandas",
  "geopandas",
  "matplotlib",
  "scipy",
  "tol-colors",
  "ipympl",
  "openpyxl",
  "scikit-learn",
  "rasterio",
  "rasterstats",
  "pip",
]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
